wit_bindgen::generate!({
    path: concat!(env!("OUT_DIR"), "/wit"),
    world: "extension",
    pub_export_macro: true,
    with: {
        "sloper:api/errors@0.1.0": generate,
        "sloper:api/credentials@0.1.0": generate,
        "sloper:api/sources@0.1.0": generate,
        "sloper:api/resources@0.1.0": generate,
        "sloper:api/log@0.1.0": generate,
        "wasi:cli/environment@0.2.12": wasip2::cli::environment,
        "wasi:cli/exit@0.2.12": wasip2::cli::exit,
        "wasi:cli/stdin@0.2.12": wasip2::cli::stdin,
        "wasi:cli/stdout@0.2.12": wasip2::cli::stdout,
        "wasi:cli/stderr@0.2.12": wasip2::cli::stderr,
        "wasi:cli/terminal-input@0.2.12": wasip2::cli::terminal_input,
        "wasi:cli/terminal-output@0.2.12": wasip2::cli::terminal_output,
        "wasi:cli/terminal-stdin@0.2.12": wasip2::cli::terminal_stdin,
        "wasi:cli/terminal-stdout@0.2.12": wasip2::cli::terminal_stdout,
        "wasi:cli/terminal-stderr@0.2.12": wasip2::cli::terminal_stderr,
        "wasi:clocks/monotonic-clock@0.2.12": wasip2::clocks::monotonic_clock,
        "wasi:clocks/wall-clock@0.2.12": wasip2::clocks::wall_clock,
        "wasi:filesystem/types@0.2.12": wasip2::filesystem::types,
        "wasi:filesystem/preopens@0.2.12": wasip2::filesystem::preopens,
        "wasi:http/types@0.2.12": wasip2::http::types,
        "wasi:http/outgoing-handler@0.2.12": wasip2::http::outgoing_handler,
        "wasi:io/error@0.2.12": wasip2::io::error,
        "wasi:io/poll@0.2.12": wasip2::io::poll,
        "wasi:io/streams@0.2.12": wasip2::io::streams,
        "wasi:random/random@0.2.12": wasip2::random::random,
        "wasi:random/insecure@0.2.12": wasip2::random::insecure,
        "wasi:random/insecure-seed@0.2.12": wasip2::random::insecure_seed,
        "wasi:sockets/network@0.2.12": wasip2::sockets::network,
        "wasi:sockets/instance-network@0.2.12": wasip2::sockets::instance_network,
        "wasi:sockets/udp@0.2.12": wasip2::sockets::udp,
        "wasi:sockets/udp-create-socket@0.2.12": wasip2::sockets::udp_create_socket,
        "wasi:sockets/tcp@0.2.12": wasip2::sockets::tcp,
        "wasi:sockets/tcp-create-socket@0.2.12": wasip2::sockets::tcp_create_socket,
        "wasi:sockets/ip-name-lookup@0.2.12": wasip2::sockets::ip_name_lookup,
    },
});
